theme: jekyll-theme-midnight

sass:
  sass_dir:          _sass
  style:            :compressed

# Gems
plugins:
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
